// Code generated by MockGen. DO NOT EDIT.
// Source: ../attestation/attestation.go
//
// Generated by this command:
//
//	mockgen -source=../attestation/attestation.go -destination=mock_attestation.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	attestation "github.com/alanmeadows/otto/internal/attestation"
	gomock "go.uber.org/mock/gomock"
)

// MockVerifier is a mock of Verifier interface.
type MockVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockVerifierMockRecorder
	isgomock struct{}
}

// MockVerifierMockRecorder is the mock recorder for MockVerifier.
type MockVerifierMockRecorder struct {
	mock *MockVerifier
}

// NewMockVerifier creates a new mock instance.
func NewMockVerifier(ctrl *gomock.Controller) *MockVerifier {
	mock := &MockVerifier{ctrl: ctrl}
	mock.recorder = &MockVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifier) EXPECT() *MockVerifierMockRecorder {
	return m.recorder
}

// Attest mocks base method.
func (m *MockVerifier) Attest(ctx context.Context, guardianName string, state attestation.PlatformState) (*attestation.AttestationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attest", ctx, guardianName, state)
	ret0, _ := ret[0].(*attestation.AttestationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attest indicates an expected call of Attest.
func (mr *MockVerifierMockRecorder) Attest(ctx, guardianName, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attest", reflect.TypeOf((*MockVerifier)(nil).Attest), ctx, guardianName, state)
}

// GetCertificate mocks base method.
func (m *MockVerifier) GetCertificate(ctx context.Context, vmID string) (*attestation.HealthCertificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificate", ctx, vmID)
	ret0, _ := ret[0].(*attestation.HealthCertificate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCertificate indicates an expected call of GetCertificate.
func (mr *MockVerifierMockRecorder) GetCertificate(ctx, vmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificate", reflect.TypeOf((*MockVerifier)(nil).GetCertificate), ctx, vmID)
}

// RevokeCertificate mocks base method.
func (m *MockVerifier) RevokeCertificate(ctx context.Context, vmID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeCertificate", ctx, vmID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeCertificate indicates an expected call of RevokeCertificate.
func (mr *MockVerifierMockRecorder) RevokeCertificate(ctx, vmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeCertificate", reflect.TypeOf((*MockVerifier)(nil).RevokeCertificate), ctx, vmID)
}
