// Code generated by MockGen. DO NOT EDIT.
// Source: ../guardian/guardian.go
//
// Generated by this command:
//
//	mockgen -source=../guardian/guardian.go -destination=mock_guardian.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	guardian "github.com/alanmeadows/otto/internal/guardian"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CreateGuardian mocks base method.
func (m *MockManager) CreateGuardian(ctx context.Context, name, certThumbprint string) (*guardian.Guardian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGuardian", ctx, name, certThumbprint)
	ret0, _ := ret[0].(*guardian.Guardian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGuardian indicates an expected call of CreateGuardian.
func (mr *MockManagerMockRecorder) CreateGuardian(ctx, name, certThumbprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGuardian", reflect.TypeOf((*MockManager)(nil).CreateGuardian), ctx, name, certThumbprint)
}

// DeleteGuardian mocks base method.
func (m *MockManager) DeleteGuardian(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGuardian", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGuardian indicates an expected call of DeleteGuardian.
func (mr *MockManagerMockRecorder) DeleteGuardian(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGuardian", reflect.TypeOf((*MockManager)(nil).DeleteGuardian), ctx, name)
}

// GetGuardian mocks base method.
func (m *MockManager) GetGuardian(ctx context.Context, name string) (*guardian.Guardian, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuardian", ctx, name)
	ret0, _ := ret[0].(*guardian.Guardian)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuardian indicates an expected call of GetGuardian.
func (mr *MockManagerMockRecorder) GetGuardian(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuardian", reflect.TypeOf((*MockManager)(nil).GetGuardian), ctx, name)
}

// ListHosts mocks base method.
func (m *MockManager) ListHosts(ctx context.Context, guardianName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHosts", ctx, guardianName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHosts indicates an expected call of ListHosts.
func (mr *MockManagerMockRecorder) ListHosts(ctx, guardianName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHosts", reflect.TypeOf((*MockManager)(nil).ListHosts), ctx, guardianName)
}

// RegisterHost mocks base method.
func (m *MockManager) RegisterHost(ctx context.Context, reg guardian.HostRegistration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterHost", ctx, reg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterHost indicates an expected call of RegisterHost.
func (mr *MockManagerMockRecorder) RegisterHost(ctx, reg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHost", reflect.TypeOf((*MockManager)(nil).RegisterHost), ctx, reg)
}

// UnregisterHost mocks base method.
func (m *MockManager) UnregisterHost(ctx context.Context, hostName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterHost", ctx, hostName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterHost indicates an expected call of UnregisterHost.
func (mr *MockManagerMockRecorder) UnregisterHost(ctx, hostName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterHost", reflect.TypeOf((*MockManager)(nil).UnregisterHost), ctx, hostName)
}
