version: 2

builds:
  - id: otto
    binary: otto
    main: ./cmd/otto
    ldflags:
      - -X github.com/alanmeadows/otto/internal/cli.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: otto
    builds:
      - otto
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    include:
      - "^feat"
      - "^fix"
      - "^perf"
      - "^refactor"
